### PR TITLE
feat: add branch suffix

### PR DESCRIPTION
**Pull request by various999stars**
# Implementations
- add branch suffix.

# Review points
- is fit to this repo.

# Attentions
- nothing special.

### CODE REVIEW

**Comment by various999stars** [comment]
https://github.com/various999stars/add-issue-links/pull/1

**Comment by various999stars** [comment]
@tktcorporation 
now, review is ready (finally....)
I was fixing author and language of commit messages.

according to test result, it works.
but in this repo, it DOESN'T work .... I don't know why though.

would you please review at your convenience?

**Comment by various999stars** [comment]
@tktcorporation 
Sorry for late reply...
I misunderstood that the code needed to be fixed. But it wasn't necessary.

`92.hoge` works! 
thank you for notice me.

I agree to close this PR.

**Comment by tktcorporation** [comment]
@various999stars 

> `92.hoge` works!

Great!

I'm going to close this PR and the Issue.
Thank you for your contributes!

**Pull request closed without merging**
